platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'RCloudMessage-alipay' do

pod 'RedpacketAliAuthLib'

end

target 'RCloudMessage-JDpay' do
    
        pod 'RedpacketLib'
    
    
end
