platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'RCloudMessage-alipay' do

pod 'RedpacketAliAuthLib'

end

target 'RCloudMessage-JDpay' do
    
    pod 'Hyphenate', '~> 3.3.2'
    
    pod 'EaseUI', :path => '../EaseUI'
    
    pod 'RedpacketLib'
    
    #pod 'Hyphenate_VideoRecoder', :path => '../HyphenateVideoRecoder'
    
end
