platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'RCloudMessage' do

pod 'RedPacketAliAuthUI', :path => 'RedpacketSDK/cocoapods-redpacket-ui-2.0.0'

end
